{% set name = "yamlloader" %}
{% set version = "1.4.1" %}
{% set sha256 = "b6fe40ecf5af596d840e920670ed3475f9813492bf6e55b24f2ad450c212bab5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - pyyaml

test:
  imports:
    - yamlloader

about:
  home: https://github.com/Phynix/yamlloader
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Loaders and dumpers for PyYAML

  description: |
    This module provides loaders and dumpers for PyYAML. Currently, an OrderedDict
    loader/dumper is implemented, allowing to keep items order when loading respectively
    dumping a file from/to an OrderedDict.
  dev_url: https://github.com/Phynix/yamlloader

extra:
  recipe-maintainers:
    - jonas-eschle
    - rasmusagren
