{% set name = "yamlloader" %}
{% set version = "1.6.0" %}
{% set sha256 = "918232976c9910d079ef74b3266ff9ef674228609aa56e67718b3992940a823f" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
    - hatch-vcs
  run:
    - python >={{ python_min }}
    - pyyaml

test:
  requires:
    - python {{ python_min }}
    - pyyaml
  imports:
    - yamlloader

about:
  home: https://github.com/Phynix/yamlloader
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Loaders and dumpers for PyYAML

  description: |
    This module provides loaders and dumpers for PyYAML. Currently, an OrderedDict
    loader/dumper is implemented, allowing to keep items order when loading respectively
    dumping a file from/to an OrderedDict.
  dev_url: https://github.com/Phynix/yamlloader

extra:
  recipe-maintainers:
    - jonas-eschle
    - rasmusagren
