{% set name = "yamlloader" %}
{% set version = "1.2.2" %}
{% set sha256 = "35669fd7b9f8c6b38db861a51701542c42672b46e8ab63253486a8cb8377b687" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - pyyaml

test:
  imports:
    - yamlloader

about:
  home: https://github.com/Phynix/yamlloader
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Loaders and dumpers for PyYAML

  description: |
    This module provides loaders and dumpers for PyYAML. Currently, an OrderedDict
    loader/dumper is implemented, allowing to keep items order when loading respectively
    dumping a file from/to an OrderedDict.
  dev_url: https://github.com/Phynix/yamlloader

extra:
  recipe-maintainers:
    - mayou36
    - rasmusagren
