{% set name = "yamlloader" %}
{% set version = "0.5.5" %}
{% set sha256 = "dcab5f16b39bb03d10dda4cd4f30c943675ec4c7771807fc67e7f1bb319bf4c8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python
    - pyyaml

test:
  imports:
    - yamlloader

about:
  home: https://github.com/Phynix/yamlloader
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Loaders and dumpers for PyYAML'

  description: |
    This module provides loaders and dumpers for PyYAML. Currently, an OrderedDict
    loader/dumper is implemented, allowing to keep items order when loading respectively
    dumping a file from/to an OrderedDict.
  dev_url: https://github.com/Phynix/yamlloader

extra:
  recipe-maintainers:
    - mayou36
    - rasmusagren
