travis:
  secure:
    BINSTAR_TOKEN: oCIHpR+pGocorxC1xuFM3LO3cybv+ivh+0ntBTskmR9Vg+rUO3yLRVI3EMVJA55GG3d4W5mEr+SCUM9PR+9pJ6FBxzJyLSJWf14NnASAP2kzGvAMEOJ0bAH2r4N8fAxY4rm+mBXzJ4i/Db4q4bvbn5I6X+m8f+YXioJSphI1APpWUGf7U1oyYJKHWmTCgkZjok/BFuBaEquR3P87Z1r/OQOBkbZRyLutzGhOTVT5AVLgdwk2SAFD8qtXhMmapeDd8auni95HRCj3u2YXbDkmGp7PV6ykFyZEE1Sbr3g1+Q6sV1us81NUU5gdcu+MNhxGclz6hPWAOyrRlvLhUly5szbApCZBzpBIx2ZEwuhtfmNp08NNKhekNZs8TAX8rpSYXWYQERks9iQcBPM/KbZeBClYxp9lcmL2Xtbg7/8l0X/vKqD/DUB7j88cOMW5V1oSqj8yo63H6V87fKfoZ8N2CCWWqe5RphZiHlB3TxOaxLyqxTnwd8vxEGsFxLgUAXyVh9fcmPxeICPsJNIQPnDRaj8VD+A4jg4lIn/JdOWmgigiIm+tKADM2WUrjyvNaaNSOCf2ehdNKvuGy05Oa3/Wja83tgYpK1km3hVJj4Umnesmv7m0ETvD5bnGnNKCv/N1QGthTB46U5WjSPGUIFGZwGgvJrSORcFvvIBNUpe3N3c=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
conda_forge_output_validation: false
