travis:
  secure:
    BINSTAR_TOKEN: Lm9otd4ctTFXYefVBVO1xwe0+VBGvl1VioiZgRd0Smhd9mSP5YJTSU3lZ7TdWFz9/wedjhQSpmWRlzo1Pb1P8AIGR5lHomQWbAwRENfIg3tgGeZMuJoWoZFwmD5IpgxxrIO7/cQZ5ZqJTl04shCupVnecoupBu03FSyXkzHe6z/flH+Fp/VWpEQ1ZtFx+zCiJPmMHN7fjkYF56+VpVu0S23konYxJSk2yfkFeQKDg9T0JGdBu/yJF2Kc+S3GlzMPIeTThNssBQldutLfb7d+dEFQQF1j14Gmp0u8mwLq00QK++8TirJKo9hMZzJydOAFf6A6w4r4ApkTm2q+co0mxDuicIWVxcUscNeupgKfa8VE1KtcuVVQxW7YsWSnT95U/ElTNpcROdh1B3vKW7z3ZkDIwLe7hKufkal5TDYmrvjjgLZveavgT/ctTEx0ftGCNUNod0ikEWQUs+wypDygIdYQomC/i1+Vxf6CY3VK+DjxvhDCOakM1ewk2TBuTZlZGe2cKs43AsIO7/4gbua7AfAsmgKiM34raocDFNaYEmVAb/JPMSNVkvYSZlGeJroBDEDQhKw7wpYtposJwEuNmMaVMmn8T6yp/jzJ9FKQl/E+KAEqbXecD8fuDIGhX+DYQAYAwraepOADoli3ip3BlyWUs3UsRAWwxXIA90UemEE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
